title: Ya-Peng Fu
tagline: Ph.D. Student in Economics
description: Ph.D. student in Economics
#Comment out url when working locally to resolve base urls correctly
url: https:/fyapeng.com

# Owner/author information
owner:
  name: Ya-Peng Fu
  avatar: yapeng.png
  bio: Ph.D. Student in Economics
  email: yapengf@outlook.com
  emailq: fuyapeng@ucass.edu.cn
  cv_en: https://fyapeng.com/cv/cv_en.pdf
  cv_zh: https://fyapeng.com/cv/cv_zh.pdf
  subions: "芾椿YA"
  wechat: "yapeng_f"
  locals: "联系地址"



links:
  - title: About Me
    url: /
  - title: Research
    url: /research/
  - title: Awards
    url: /awards/
  - title: Activity
    url: /activity/


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: China/Beijing
future: true
highlighter: rouge
# markdown: kramdown
# markdown: redcarpet
# pygments: true


# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..5
  enable_coderay: false

  # coderay:
  #   coderay_line_numbers:
  #   coderay_line_numbers_start: 1
  #   coderay_tab_width: 4
  #   coderay_bold_every: 10
  #   coderay_css: class


disqus:
  shortname: yapengfu
include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "minimal-mistakes.sublime-project", "minimal-mistakes.sublime-workspace"]