title: Ya-Peng Fu
tagline: Ph.D. Student in Economics
description: Ph.D. student in Economics
#Comment out url when working locally to resolve base urls correctly
url: https://yapengf.com

# Owner/author information
owner:
  name: Ya-Peng Fu
  avatar: yapeng.png
  bio: Ph.D. Student in Economics
  email: yapengf@outlook.com
  emailq: fuyapeng@ucass.edu.cn
  cv_en: https://yapengf.com/cv/cv_en.pdf
  cv_zh: https://yapengf.com/cv/cv_zh.pdf
  subions: "芾椿YA"
  wechat: "yapeng_f"
  locals: "联系地址"
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  # twitter: lancecai2002
  # github: GuangLun2000
  # linkedin: hanlincai
  # scholar: https://scholar.google.com/citations?user=8igSoWgAAAAJ
  # bilibili: 594030035
  # researchgate: https://www.researchgate.net/profile/Hanlin-Cai
  # zhihu: https://www.zhihu.com/people/chlire
  # facebook: caihanlin2002
  # instagram: lancecai2002
  # lastfm:
  # tumblr:
  # For Google Authorship https://plus.google.com/authorship
  # google_plus:

# Analytics and webmaster tools stuff goes here
# https://search.google.com/search-console/ownership
# google_verify: "SkiyuGpJOKT74vv5GmXLvYXXDkXy4v8VWPtbelYz3Hs"

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
# bing_verify: ""

# Links to include in top navigation
# For external links add external: true
links:
  - title: About Me
    url: /
  - title: Research
    url: /research/
  - title: Awards
    url: /awards/
  - title: Activity
    url: /activity/


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: China/Beijing
future: true
highlighter: rouge
# markdown: kramdown
# markdown: redcarpet
# pygments: true


# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title


kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..5
  enable_coderay: false

  # coderay:
  #   coderay_line_numbers:
  #   coderay_line_numbers_start: 1
  #   coderay_tab_width: 4
  #   coderay_bold_every: 10
  #   coderay_css: class


disqus:
  shortname: yapengfu
include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "minimal-mistakes.sublime-project", "minimal-mistakes.sublime-workspace"]